import "~/styles/globals.css"; 

import { type Metadata } from "next";
import { Geist } from "next/font/google";

export const metadata: Metadata = {
  title: "Pokédex-Binpart",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/poke.png" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

/**
 * RootLayout envuelve toda la aplicación y define la estructura base del HTML.
 *
 * - Aplica la fuente Geist a todo el sitio.
 * - Incluye los estilos globales.
 * - Renderiza los children (todas las páginas y componentes).
 *
 * @param children - Elementos React que representan el contenido de cada página.
 * @returns JSX con la estructura base del documento.
 */
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}> 
      <body>{children}</body>
    </html>
  );
}